package com.example.sb.service.base;

import com.example.sb.model.Entity1;
import com.example.sb.service.Entity1Service;
import com.example.sb.service.persistence.Entity1Persistence;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.bean.IdentifiableBean;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.service.BaseServiceImpl;
import com.liferay.portal.service.persistence.UserPersistence;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the entity1 remote service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.example.sb.service.impl.Entity1ServiceImpl}.
 * </p>
 *
 * @author akimov
 * @see com.example.sb.service.impl.Entity1ServiceImpl
 * @see com.example.sb.service.Entity1ServiceUtil
 * @generated
 */
public abstract class Entity1ServiceBaseImpl extends BaseServiceImpl
    implements Entity1Service, IdentifiableBean {
    @BeanReference(type = com.example.sb.service.Entity1LocalService.class)
    protected com.example.sb.service.Entity1LocalService entity1LocalService;
    @BeanReference(type = com.example.sb.service.Entity1Service.class)
    protected com.example.sb.service.Entity1Service entity1Service;
    @BeanReference(type = Entity1Persistence.class)
    protected Entity1Persistence entity1Persistence;
    @BeanReference(type = com.liferay.counter.service.CounterLocalService.class)
    protected com.liferay.counter.service.CounterLocalService counterLocalService;
    @BeanReference(type = com.liferay.portal.service.ResourceLocalService.class)
    protected com.liferay.portal.service.ResourceLocalService resourceLocalService;
    @BeanReference(type = com.liferay.portal.service.UserLocalService.class)
    protected com.liferay.portal.service.UserLocalService userLocalService;
    @BeanReference(type = com.liferay.portal.service.UserService.class)
    protected com.liferay.portal.service.UserService userService;
    @BeanReference(type = UserPersistence.class)
    protected UserPersistence userPersistence;
    private String _beanIdentifier;
    private ClassLoader _classLoader;
    private Entity1ServiceClpInvoker _clpInvoker = new Entity1ServiceClpInvoker();

    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. Always use {@link com.example.sb.service.Entity1ServiceUtil} to access the entity1 remote service.
     */

    /**
     * Returns the entity1 local service.
     *
     * @return the entity1 local service
     */
    public com.example.sb.service.Entity1LocalService getEntity1LocalService() {
        return entity1LocalService;
    }

    /**
     * Sets the entity1 local service.
     *
     * @param entity1LocalService the entity1 local service
     */
    public void setEntity1LocalService(
        com.example.sb.service.Entity1LocalService entity1LocalService) {
        this.entity1LocalService = entity1LocalService;
    }

    /**
     * Returns the entity1 remote service.
     *
     * @return the entity1 remote service
     */
    public com.example.sb.service.Entity1Service getEntity1Service() {
        return entity1Service;
    }

    /**
     * Sets the entity1 remote service.
     *
     * @param entity1Service the entity1 remote service
     */
    public void setEntity1Service(
        com.example.sb.service.Entity1Service entity1Service) {
        this.entity1Service = entity1Service;
    }

    /**
     * Returns the entity1 persistence.
     *
     * @return the entity1 persistence
     */
    public Entity1Persistence getEntity1Persistence() {
        return entity1Persistence;
    }

    /**
     * Sets the entity1 persistence.
     *
     * @param entity1Persistence the entity1 persistence
     */
    public void setEntity1Persistence(Entity1Persistence entity1Persistence) {
        this.entity1Persistence = entity1Persistence;
    }

    /**
     * Returns the counter local service.
     *
     * @return the counter local service
     */
    public com.liferay.counter.service.CounterLocalService getCounterLocalService() {
        return counterLocalService;
    }

    /**
     * Sets the counter local service.
     *
     * @param counterLocalService the counter local service
     */
    public void setCounterLocalService(
        com.liferay.counter.service.CounterLocalService counterLocalService) {
        this.counterLocalService = counterLocalService;
    }

    /**
     * Returns the resource local service.
     *
     * @return the resource local service
     */
    public com.liferay.portal.service.ResourceLocalService getResourceLocalService() {
        return resourceLocalService;
    }

    /**
     * Sets the resource local service.
     *
     * @param resourceLocalService the resource local service
     */
    public void setResourceLocalService(
        com.liferay.portal.service.ResourceLocalService resourceLocalService) {
        this.resourceLocalService = resourceLocalService;
    }

    /**
     * Returns the user local service.
     *
     * @return the user local service
     */
    public com.liferay.portal.service.UserLocalService getUserLocalService() {
        return userLocalService;
    }

    /**
     * Sets the user local service.
     *
     * @param userLocalService the user local service
     */
    public void setUserLocalService(
        com.liferay.portal.service.UserLocalService userLocalService) {
        this.userLocalService = userLocalService;
    }

    /**
     * Returns the user remote service.
     *
     * @return the user remote service
     */
    public com.liferay.portal.service.UserService getUserService() {
        return userService;
    }

    /**
     * Sets the user remote service.
     *
     * @param userService the user remote service
     */
    public void setUserService(
        com.liferay.portal.service.UserService userService) {
        this.userService = userService;
    }

    /**
     * Returns the user persistence.
     *
     * @return the user persistence
     */
    public UserPersistence getUserPersistence() {
        return userPersistence;
    }

    /**
     * Sets the user persistence.
     *
     * @param userPersistence the user persistence
     */
    public void setUserPersistence(UserPersistence userPersistence) {
        this.userPersistence = userPersistence;
    }

    public void afterPropertiesSet() {
        Class<?> clazz = getClass();

        _classLoader = clazz.getClassLoader();
    }

    public void destroy() {
    }

    /**
     * Returns the Spring bean ID for this bean.
     *
     * @return the Spring bean ID for this bean
     */
    @Override
    public String getBeanIdentifier() {
        return _beanIdentifier;
    }

    /**
     * Sets the Spring bean ID for this bean.
     *
     * @param beanIdentifier the Spring bean ID for this bean
     */
    @Override
    public void setBeanIdentifier(String beanIdentifier) {
        _beanIdentifier = beanIdentifier;
    }

    @Override
    public Object invokeMethod(String name, String[] parameterTypes,
        Object[] arguments) throws Throwable {
        Thread currentThread = Thread.currentThread();

        ClassLoader contextClassLoader = currentThread.getContextClassLoader();

        if (contextClassLoader != _classLoader) {
            currentThread.setContextClassLoader(_classLoader);
        }

        try {
            return _clpInvoker.invokeMethod(name, parameterTypes, arguments);
        } finally {
            if (contextClassLoader != _classLoader) {
                currentThread.setContextClassLoader(contextClassLoader);
            }
        }
    }

    protected Class<?> getModelClass() {
        return Entity1.class;
    }

    protected String getModelClassName() {
        return Entity1.class.getName();
    }

    /**
     * Performs an SQL query.
     *
     * @param sql the sql query
     */
    protected void runSQL(String sql) throws SystemException {
        try {
            DataSource dataSource = entity1Persistence.getDataSource();

            SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
                    sql, new int[0]);

            sqlUpdate.update();
        } catch (Exception e) {
            throw new SystemException(e);
        }
    }
}
