package com.example.sb.model.impl;

import com.example.sb.model.EntityA;
import com.example.sb.service.EntityALocalServiceUtil;

import com.liferay.portal.kernel.exception.SystemException;

/**
 * The extended model base implementation for the EntityA service. Represents a row in the &quot;SB_EntityA&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link EntityAImpl}.
 * </p>
 *
 * @author akimov
 * @see EntityAImpl
 * @see com.example.sb.model.EntityA
 * @generated
 */
public abstract class EntityABaseImpl extends EntityAModelImpl
    implements EntityA {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a entity a model instance should use the {@link EntityA} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            EntityALocalServiceUtil.addEntityA(this);
        } else {
            EntityALocalServiceUtil.updateEntityA(this);
        }
    }
}
