package com.example.sb.model.impl;

import com.example.sb.model.Entity2;

/**
 * The extended model base implementation for the Entity2 service. Represents a row in the &quot;SB_Entity2&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link Entity2Impl}.
 * </p>
 *
 * @author akimov
 * @see Entity2Impl
 * @see com.example.sb.model.Entity2
 * @generated
 */
public abstract class Entity2BaseImpl extends Entity2ModelImpl
    implements Entity2 {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a entity2 model instance should use the {@link Entity2} interface instead.
     */
}
