package com.example.sb.model.impl;

import com.example.sb.model.PRRegistration;
import com.example.sb.service.PRRegistrationLocalServiceUtil;

import com.liferay.portal.kernel.exception.SystemException;

/**
 * The extended model base implementation for the PRRegistration service. Represents a row in the &quot;SB_PRRegistration&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link PRRegistrationImpl}.
 * </p>
 *
 * @author akimov
 * @see PRRegistrationImpl
 * @see com.example.sb.model.PRRegistration
 * @generated
 */
public abstract class PRRegistrationBaseImpl extends PRRegistrationModelImpl
    implements PRRegistration {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a p r registration model instance should use the {@link PRRegistration} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            PRRegistrationLocalServiceUtil.addPRRegistration(this);
        } else {
            PRRegistrationLocalServiceUtil.updatePRRegistration(this);
        }
    }
}
