package com.example.sb.model.impl;

import com.example.sb.model.PRUser;
import com.example.sb.model.PRUserModel;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;
import com.liferay.portal.util.PortalUtil;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import java.io.Serializable;

import java.sql.Types;

import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the PRUser service. Represents a row in the &quot;SB_PRUser&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.example.sb.model.PRUserModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link PRUserImpl}.
 * </p>
 *
 * @author akimov
 * @see PRUserImpl
 * @see com.example.sb.model.PRUser
 * @see com.example.sb.model.PRUserModel
 * @generated
 */
public class PRUserModelImpl extends BaseModelImpl<PRUser>
    implements PRUserModel {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a p r user model instance should use the {@link com.example.sb.model.PRUser} interface instead.
     */
    public static final String TABLE_NAME = "SB_PRUser";
    public static final Object[][] TABLE_COLUMNS = {
            { "prUserId", Types.BIGINT },
            { "firstName", Types.VARCHAR },
            { "lastName", Types.VARCHAR }
        };
    public static final String TABLE_SQL_CREATE = "create table SB_PRUser (prUserId LONG not null primary key,firstName VARCHAR(75) null,lastName VARCHAR(75) null)";
    public static final String TABLE_SQL_DROP = "drop table SB_PRUser";
    public static final String ORDER_BY_JPQL = " ORDER BY prUser.prUserId ASC";
    public static final String ORDER_BY_SQL = " ORDER BY SB_PRUser.prUserId ASC";
    public static final String DATA_SOURCE = "liferayDataSource";
    public static final String SESSION_FACTORY = "liferaySessionFactory";
    public static final String TX_MANAGER = "liferayTransactionManager";
    public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.entity.cache.enabled.com.example.sb.model.PRUser"),
            true);
    public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.finder.cache.enabled.com.example.sb.model.PRUser"),
            true);
    public static final boolean COLUMN_BITMASK_ENABLED = false;
    public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
                "lock.expiration.time.com.example.sb.model.PRUser"));
    private static ClassLoader _classLoader = PRUser.class.getClassLoader();
    private static Class<?>[] _escapedModelInterfaces = new Class[] { PRUser.class };
    private long _prUserId;
    private String _prUserUuid;
    private String _firstName;
    private String _lastName;
    private PRUser _escapedModel;

    public PRUserModelImpl() {
    }

    @Override
    public long getPrimaryKey() {
        return _prUserId;
    }

    @Override
    public void setPrimaryKey(long primaryKey) {
        setPrUserId(primaryKey);
    }

    @Override
    public Serializable getPrimaryKeyObj() {
        return _prUserId;
    }

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj) {
        setPrimaryKey(((Long) primaryKeyObj).longValue());
    }

    @Override
    public Class<?> getModelClass() {
        return PRUser.class;
    }

    @Override
    public String getModelClassName() {
        return PRUser.class.getName();
    }

    @Override
    public Map<String, Object> getModelAttributes() {
        Map<String, Object> attributes = new HashMap<String, Object>();

        attributes.put("prUserId", getPrUserId());
        attributes.put("firstName", getFirstName());
        attributes.put("lastName", getLastName());

        return attributes;
    }

    @Override
    public void setModelAttributes(Map<String, Object> attributes) {
        Long prUserId = (Long) attributes.get("prUserId");

        if (prUserId != null) {
            setPrUserId(prUserId);
        }

        String firstName = (String) attributes.get("firstName");

        if (firstName != null) {
            setFirstName(firstName);
        }

        String lastName = (String) attributes.get("lastName");

        if (lastName != null) {
            setLastName(lastName);
        }
    }

    @Override
    public long getPrUserId() {
        return _prUserId;
    }

    @Override
    public void setPrUserId(long prUserId) {
        _prUserId = prUserId;
    }

    @Override
    public String getPrUserUuid() throws SystemException {
        return PortalUtil.getUserValue(getPrUserId(), "uuid", _prUserUuid);
    }

    @Override
    public void setPrUserUuid(String prUserUuid) {
        _prUserUuid = prUserUuid;
    }

    @Override
    public String getFirstName() {
        if (_firstName == null) {
            return StringPool.BLANK;
        } else {
            return _firstName;
        }
    }

    @Override
    public void setFirstName(String firstName) {
        _firstName = firstName;
    }

    @Override
    public String getLastName() {
        if (_lastName == null) {
            return StringPool.BLANK;
        } else {
            return _lastName;
        }
    }

    @Override
    public void setLastName(String lastName) {
        _lastName = lastName;
    }

    @Override
    public ExpandoBridge getExpandoBridge() {
        return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
            PRUser.class.getName(), getPrimaryKey());
    }

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
        ExpandoBridge expandoBridge = getExpandoBridge();

        expandoBridge.setAttributes(serviceContext);
    }

    @Override
    public PRUser toEscapedModel() {
        if (_escapedModel == null) {
            _escapedModel = (PRUser) ProxyUtil.newProxyInstance(_classLoader,
                    _escapedModelInterfaces, new AutoEscapeBeanHandler(this));
        }

        return _escapedModel;
    }

    @Override
    public Object clone() {
        PRUserImpl prUserImpl = new PRUserImpl();

        prUserImpl.setPrUserId(getPrUserId());
        prUserImpl.setFirstName(getFirstName());
        prUserImpl.setLastName(getLastName());

        prUserImpl.resetOriginalValues();

        return prUserImpl;
    }

    @Override
    public int compareTo(PRUser prUser) {
        long primaryKey = prUser.getPrimaryKey();

        if (getPrimaryKey() < primaryKey) {
            return -1;
        } else if (getPrimaryKey() > primaryKey) {
            return 1;
        } else {
            return 0;
        }
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }

        if (!(obj instanceof PRUser)) {
            return false;
        }

        PRUser prUser = (PRUser) obj;

        long primaryKey = prUser.getPrimaryKey();

        if (getPrimaryKey() == primaryKey) {
            return true;
        } else {
            return false;
        }
    }

    @Override
    public int hashCode() {
        return (int) getPrimaryKey();
    }

    @Override
    public void resetOriginalValues() {
    }

    @Override
    public CacheModel<PRUser> toCacheModel() {
        PRUserCacheModel prUserCacheModel = new PRUserCacheModel();

        prUserCacheModel.prUserId = getPrUserId();

        prUserCacheModel.firstName = getFirstName();

        String firstName = prUserCacheModel.firstName;

        if ((firstName != null) && (firstName.length() == 0)) {
            prUserCacheModel.firstName = null;
        }

        prUserCacheModel.lastName = getLastName();

        String lastName = prUserCacheModel.lastName;

        if ((lastName != null) && (lastName.length() == 0)) {
            prUserCacheModel.lastName = null;
        }

        return prUserCacheModel;
    }

    @Override
    public String toString() {
        StringBundler sb = new StringBundler(7);

        sb.append("{prUserId=");
        sb.append(getPrUserId());
        sb.append(", firstName=");
        sb.append(getFirstName());
        sb.append(", lastName=");
        sb.append(getLastName());
        sb.append("}");

        return sb.toString();
    }

    @Override
    public String toXmlString() {
        StringBundler sb = new StringBundler(13);

        sb.append("<model><model-name>");
        sb.append("com.example.sb.model.PRUser");
        sb.append("</model-name>");

        sb.append(
            "<column><column-name>prUserId</column-name><column-value><![CDATA[");
        sb.append(getPrUserId());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>firstName</column-name><column-value><![CDATA[");
        sb.append(getFirstName());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>lastName</column-name><column-value><![CDATA[");
        sb.append(getLastName());
        sb.append("]]></column-value></column>");

        sb.append("</model>");

        return sb.toString();
    }
}
