package com.example.sb.model;

import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the EntityA service. Represents a row in the &quot;SB_EntityA&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.example.sb.model.impl.EntityAModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.example.sb.model.impl.EntityAImpl}.
 * </p>
 *
 * @author akimov
 * @see EntityA
 * @see com.example.sb.model.impl.EntityAImpl
 * @see com.example.sb.model.impl.EntityAModelImpl
 * @generated
 */
public interface EntityAModel extends BaseModel<EntityA> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a entity a model instance should use the {@link EntityA} interface instead.
     */

    /**
     * Returns the primary key of this entity a.
     *
     * @return the primary key of this entity a
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this entity a.
     *
     * @param primaryKey the primary key of this entity a
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the ID of this entity a.
     *
     * @return the ID of this entity a
     */
    public long getId();

    /**
     * Sets the ID of this entity a.
     *
     * @param id the ID of this entity a
     */
    public void setId(long id);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(com.example.sb.model.EntityA entityA);

    @Override
    public int hashCode();

    @Override
    public CacheModel<com.example.sb.model.EntityA> toCacheModel();

    @Override
    public com.example.sb.model.EntityA toEscapedModel();

    @Override
    public com.example.sb.model.EntityA toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
