package com.example.sb.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the Entity2 service. Represents a row in the &quot;SB_Entity2&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.example.sb.model.impl.Entity2ModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.example.sb.model.impl.Entity2Impl}.
 * </p>
 *
 * @author akimov
 * @see Entity2
 * @see com.example.sb.model.impl.Entity2Impl
 * @see com.example.sb.model.impl.Entity2ModelImpl
 * @generated
 */
public interface Entity2Model extends BaseModel<Entity2> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a entity2 model instance should use the {@link Entity2} interface instead.
     */

    /**
     * Returns the primary key of this entity2.
     *
     * @return the primary key of this entity2
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this entity2.
     *
     * @param primaryKey the primary key of this entity2
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the ID of this entity2.
     *
     * @return the ID of this entity2
     */
    public long getId();

    /**
     * Sets the ID of this entity2.
     *
     * @param id the ID of this entity2
     */
    public void setId(long id);

    /**
     * Returns the field2 of this entity2.
     *
     * @return the field2 of this entity2
     */
    @AutoEscape
    public String getField2();

    /**
     * Sets the field2 of this entity2.
     *
     * @param Field2 the field2 of this entity2
     */
    public void setField2(String Field2);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(com.example.sb.model.Entity2 entity2);

    @Override
    public int hashCode();

    @Override
    public CacheModel<com.example.sb.model.Entity2> toCacheModel();

    @Override
    public com.example.sb.model.Entity2 toEscapedModel();

    @Override
    public com.example.sb.model.Entity2 toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
