package com.example.sb.model;

import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the PRRegistration service. Represents a row in the &quot;SB_PRRegistration&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.example.sb.model.impl.PRRegistrationModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.example.sb.model.impl.PRRegistrationImpl}.
 * </p>
 *
 * @author akimov
 * @see PRRegistration
 * @see com.example.sb.model.impl.PRRegistrationImpl
 * @see com.example.sb.model.impl.PRRegistrationModelImpl
 * @generated
 */
public interface PRRegistrationModel extends BaseModel<PRRegistration> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a p r registration model instance should use the {@link PRRegistration} interface instead.
     */

    /**
     * Returns the primary key of this p r registration.
     *
     * @return the primary key of this p r registration
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this p r registration.
     *
     * @param primaryKey the primary key of this p r registration
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the registration ID of this p r registration.
     *
     * @return the registration ID of this p r registration
     */
    public long getRegistrationId();

    /**
     * Sets the registration ID of this p r registration.
     *
     * @param registrationId the registration ID of this p r registration
     */
    public void setRegistrationId(long registrationId);

    /**
     * Returns the pr user ID of this p r registration.
     *
     * @return the pr user ID of this p r registration
     */
    public long getPrUserId();

    /**
     * Sets the pr user ID of this p r registration.
     *
     * @param prUserId the pr user ID of this p r registration
     */
    public void setPrUserId(long prUserId);

    /**
     * Returns the pr user uuid of this p r registration.
     *
     * @return the pr user uuid of this p r registration
     * @throws SystemException if a system exception occurred
     */
    public String getPrUserUuid() throws SystemException;

    /**
     * Sets the pr user uuid of this p r registration.
     *
     * @param prUserUuid the pr user uuid of this p r registration
     */
    public void setPrUserUuid(String prUserUuid);

    /**
     * Returns the group ID of this p r registration.
     *
     * @return the group ID of this p r registration
     */
    public long getGroupId();

    /**
     * Sets the group ID of this p r registration.
     *
     * @param groupId the group ID of this p r registration
     */
    public void setGroupId(long groupId);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(com.example.sb.model.PRRegistration prRegistration);

    @Override
    public int hashCode();

    @Override
    public CacheModel<com.example.sb.model.PRRegistration> toCacheModel();

    @Override
    public com.example.sb.model.PRRegistration toEscapedModel();

    @Override
    public com.example.sb.model.PRRegistration toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
