package com.example.sb.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the PRUser service. Represents a row in the &quot;SB_PRUser&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.example.sb.model.impl.PRUserModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.example.sb.model.impl.PRUserImpl}.
 * </p>
 *
 * @author akimov
 * @see PRUser
 * @see com.example.sb.model.impl.PRUserImpl
 * @see com.example.sb.model.impl.PRUserModelImpl
 * @generated
 */
public interface PRUserModel extends BaseModel<PRUser> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a p r user model instance should use the {@link PRUser} interface instead.
     */

    /**
     * Returns the primary key of this p r user.
     *
     * @return the primary key of this p r user
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this p r user.
     *
     * @param primaryKey the primary key of this p r user
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the pr user ID of this p r user.
     *
     * @return the pr user ID of this p r user
     */
    public long getPrUserId();

    /**
     * Sets the pr user ID of this p r user.
     *
     * @param prUserId the pr user ID of this p r user
     */
    public void setPrUserId(long prUserId);

    /**
     * Returns the pr user uuid of this p r user.
     *
     * @return the pr user uuid of this p r user
     * @throws SystemException if a system exception occurred
     */
    public String getPrUserUuid() throws SystemException;

    /**
     * Sets the pr user uuid of this p r user.
     *
     * @param prUserUuid the pr user uuid of this p r user
     */
    public void setPrUserUuid(String prUserUuid);

    /**
     * Returns the first name of this p r user.
     *
     * @return the first name of this p r user
     */
    @AutoEscape
    public String getFirstName();

    /**
     * Sets the first name of this p r user.
     *
     * @param firstName the first name of this p r user
     */
    public void setFirstName(String firstName);

    /**
     * Returns the last name of this p r user.
     *
     * @return the last name of this p r user
     */
    @AutoEscape
    public String getLastName();

    /**
     * Sets the last name of this p r user.
     *
     * @param lastName the last name of this p r user
     */
    public void setLastName(String lastName);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(com.example.sb.model.PRUser prUser);

    @Override
    public int hashCode();

    @Override
    public CacheModel<com.example.sb.model.PRUser> toCacheModel();

    @Override
    public com.example.sb.model.PRUser toEscapedModel();

    @Override
    public com.example.sb.model.PRUser toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
